<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mark Fuge">
<meta name="dcterms.date" content="2025-10-01">

<title>5&nbsp; Taking Derivatives with Automatic Differentiation – Machine Learning for Mechanical Engineering</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../part1/distribution_distance.html" rel="next">
<link href="../part1/linear_decompositions.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-fd0503e23dce65854c81c5baaade3bdf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part1/index.html">Foundational Skills</a></li><li class="breadcrumb-item"><a href="../part1/taking_derivatives.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Taking Derivatives with Automatic Differentiation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Machine Learning for Mechanical Engineering</a> 
        <div class="sidebar-tools-main">
    <a href="../Machine-Learning-for-Mechanical-Engineering.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundational Skills</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/reviewing_supervised_linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Reviewing Supervised Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/cross_validation_linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Evaluating Machine Learning Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notebooks/supervised_linear_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction to Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/linear_decompositions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review of Linear Unsupervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/taking_derivatives.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Taking Derivatives with Automatic Differentiation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/distribution_distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measuring Distribution Distances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/introduction_to_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction to Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part1/introduction_to_probabilistic_programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introduction to Probabilistic Programming</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part2/part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of Generative Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/review_neural_networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Review of Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/intro_to_GANS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to Push-Forward Generative Models – Generative Adversarial Networks (GANs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/GAN_pitfalls.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">GAN Training Pitfalls</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/OT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Optimal Transport for Generative Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/VAEs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Variational Autoencoders (VAEs)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/normalizing_flows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Normalizing Flows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/continuous_flows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">From Discrete Transformations to Continuous Flows</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/score_matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">From Continuous Flows to Score Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/diffusion_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">From Score Matching to Diffusion Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/flow_matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Flow Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/latent_generative_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Latent Generative Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/introduction_to_reinforcement_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Introduction to Deep Reinforcement Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part2/gen_models/transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Introduction to Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../part3/part3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Engineering-Specific Considerations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../part3/active_and_semisupervised_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Active and Semi-Supervised Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/helpful_tooling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Helpful Tooling for Working with and Debugging Machine Learning Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/review_of_singular_value_decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Review of Matrices and the Singular Value Decomposition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/review_of_math_and_computing_foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Reviewing Mathematical and Computational Foundations for Machine Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#automatic-differentiation" id="toc-automatic-differentiation" class="nav-link active" data-scroll-target="#automatic-differentiation"><span class="header-section-number">5.1</span> Automatic Differentiation</a>
  <ul class="collapse">
  <li><a href="#build-the-computational-graph" id="toc-build-the-computational-graph" class="nav-link" data-scroll-target="#build-the-computational-graph"><span class="header-section-number">5.1.1</span> Build the Computational Graph</a></li>
  <li><a href="#compute-the-forward-pass" id="toc-compute-the-forward-pass" class="nav-link" data-scroll-target="#compute-the-forward-pass"><span class="header-section-number">5.1.2</span> Compute the Forward Pass</a></li>
  <li><a href="#computing-forward-mode-ad-tangent-propagation" id="toc-computing-forward-mode-ad-tangent-propagation" class="nav-link" data-scroll-target="#computing-forward-mode-ad-tangent-propagation"><span class="header-section-number">5.1.3</span> Computing Forward Mode AD (tangent propagation)</a></li>
  <li><a href="#computing-reverse-mode-ad-backpropagation" id="toc-computing-reverse-mode-ad-backpropagation" class="nav-link" data-scroll-target="#computing-reverse-mode-ad-backpropagation"><span class="header-section-number">5.1.4</span> Computing Reverse Mode AD (backpropagation)</a></li>
  </ul></li>
  <li><a href="#pytorch-autograd-example-with-simple-function" id="toc-pytorch-autograd-example-with-simple-function" class="nav-link" data-scroll-target="#pytorch-autograd-example-with-simple-function"><span class="header-section-number">5.2</span> PyTorch Autograd Example with Simple Function</a>
  <ul class="collapse">
  <li><a href="#automatic-differentiation-using-pytorch" id="toc-automatic-differentiation-using-pytorch" class="nav-link" data-scroll-target="#automatic-differentiation-using-pytorch"><span class="header-section-number">5.2.1</span> Automatic Differentiation using PyTorch</a></li>
  <li><a href="#finite-differences-using-scipy" id="toc-finite-differences-using-scipy" class="nav-link" data-scroll-target="#finite-differences-using-scipy"><span class="header-section-number">5.2.2</span> Finite Differences using SciPy</a></li>
  </ul></li>
  <li><a href="#pytorch-autograd-example-with-optimization" id="toc-pytorch-autograd-example-with-optimization" class="nav-link" data-scroll-target="#pytorch-autograd-example-with-optimization"><span class="header-section-number">5.3</span> PyTorch Autograd Example with Optimization</a>
  <ul class="collapse">
  <li><a href="#using-automatic-differentiation-for-optimization" id="toc-using-automatic-differentiation-for-optimization" class="nav-link" data-scroll-target="#using-automatic-differentiation-for-optimization"><span class="header-section-number">5.3.1</span> Using Automatic Differentiation for Optimization</a></li>
  <li><a href="#l-bfgs" id="toc-l-bfgs" class="nav-link" data-scroll-target="#l-bfgs"><span class="header-section-number">5.3.2</span> L-BFGS</a></li>
  </ul></li>
  <li><a href="#demonstration-of-ad-on-verlet-integration" id="toc-demonstration-of-ad-on-verlet-integration" class="nav-link" data-scroll-target="#demonstration-of-ad-on-verlet-integration"><span class="header-section-number">5.4</span> Demonstration of AD on Verlet Integration</a>
  <ul class="collapse">
  <li><a href="#optimizing-the-damping-coefficient-via-sgd-and-ad" id="toc-optimizing-the-damping-coefficient-via-sgd-and-ad" class="nav-link" data-scroll-target="#optimizing-the-damping-coefficient-via-sgd-and-ad"><span class="header-section-number">5.4.1</span> Optimizing the Damping Coefficient via SGD and AD</a></li>
  <li><a href="#compare-the-steps-taken" id="toc-compare-the-steps-taken" class="nav-link" data-scroll-target="#compare-the-steps-taken"><span class="header-section-number">5.4.2</span> Compare the steps taken</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">5.5</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../part1/index.html">Foundational Skills</a></li><li class="breadcrumb-item"><a href="../part1/taking_derivatives.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Taking Derivatives with Automatic Differentiation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Taking Derivatives with Automatic Differentiation</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mark Fuge </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Taking derivatives with respect to functions or parameters is one of the most common and fundamental operations that we will need for Machine Learning (and in fact for Scientific Computing, in general). Throughout your life so far, you have probably learned about three main ways to compute derivatives:</p>
<ol type="1">
<li><strong>Analytical Differentiation</strong>: computing the analytical derivative manually using the rules of calculus and pencil and paper. The benefit of this approach is that it is exact, but the drawback is that it can be tedious, manual, and error-prone for complex functions. Once completed, we get a function that has the exact derivative everywhere.</li>
<li><strong>Symbolic Differentiation</strong>: using a computer algebra system (CAS) to compute the analytical derivative symbolically. The main benefit of this approach is that it is exact and can handle more complex functions than manual differentiation, but the drawback is that it can be slow and may produce very complicated expressions that are difficult to evaluate numerically (a phenomenon known as <em>expression swell</em>). This method also produces a function that has the exact derivative everywhere as a single (often very large) function.</li>
<li><strong>Numerical Differentiation</strong>: using finite difference approximations to compute the derivative numerically, for example using the formula <span class="math inline">\(\frac{df}{dx} \approx \frac{f(x+h) - f(x)}{h}\)</span> for some small <span class="math inline">\(h\)</span>. The main benefit of this approach is that it is easy to implement and can handle any function that can be evaluated numerically, but its drawbacks are that it only approximates the derivative, can be sensitive to the choice of <span class="math inline">\(h\)</span>, suffers from numerical precision issues, and only provides the derivative at a single evaluated point (unlike analytical or symbolic approaches that produce a function of the derivative that is valid everywhere).</li>
</ol>
<p>This chapter won’t cover those approaches in detail, as its main goal is to introduce you to a fourth way to compute derivatives called <em>Automatic Differentiation</em> (AD). This approach inherits some of the benefits of analytical and symbolic differentiation, in that it computes <em>exact</em> derivatives (unlike numerical differentiation). It’s main drawback is that the effort used to compute the derivatives will be only useful for a single evaluation point (similar to numerical differentiation). Unlike symbolic differentiation, AD is very efficient and does not suffer from expression swell, although it does require extra bookkeeping to keep track of intermediate values and derivatives (as we will see), which can add some memory and computational overhead.</p>
<table class="caption-top table">
<caption>Overview of different methods for computing derivatives.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 41%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Benefits</th>
<th>Drawbacks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Analytical Differentiation</td>
<td>Exact derivatives, valid everywhere</td>
<td>Tedious, manual, error-prone for complex functions</td>
</tr>
<tr class="even">
<td>Symbolic Differentiation</td>
<td>Exact derivatives, can handle complex functions</td>
<td>Slow, may produce complicated expressions (expression swell)</td>
</tr>
<tr class="odd">
<td>Numerical Differentiation</td>
<td>Easy to implement, handles any numerically evaluable function</td>
<td>Only approximates derivative, sensitive to <span class="math inline">\(h\)</span>, precision issues, pointwise</td>
</tr>
<tr class="even">
<td>Automatic Differentiation</td>
<td>Exact derivatives, efficient computation</td>
<td>More complex implementation, potential overhead</td>
</tr>
</tbody>
</table>
<p>With this overview in mind, we can now introduce Automatic Differentiation using a simple example, and then later demonstrate how to use it via some practical examples.</p>
<p><strong>Learning Objectives</strong></p>
<p>By the end of this chapter, you should be able to:</p>
<ol type="1">
<li>Build a computational graph and perform forward-mode automatic differentiation by hand.</li>
<li>Perform reverse-mode automatic differentiation (backpropagation) by hand and explain when forward or reverse mode is cheaper.</li>
<li>Use <code>torch.autograd</code>, compare it with finite differences, and recognize when either should not be trusted.</li>
<li>Use gradients in an optimizer (Adam, L-BFGS) and interpret the optimization path.</li>
<li>Differentiate through a numerical simulator to obtain sensitivities and fit physical parameters, and recognize when such gradients vanish, explode, or mislead.</li>
</ol>
<section id="automatic-differentiation" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="automatic-differentiation"><span class="header-section-number">5.1</span> Automatic Differentiation</h2>
<p>To demonstrate how Automatic Differentiation works, let’s take a simple example function, for which we can easily compute the derivatives manually/analytically, so that we can check out results. Let’s consider the function:</p>
<p><span class="math display">\[
f(x_1, x_2) = \ln(x_1) + x_1 \cdot x_2 - \sin(x_2)
\]</span></p>
<p>evaluated at <span class="math inline">\(x_1 = 2, x_2 = 5\)</span>.</p>
<p>Analytically, this function is simple enough that we could actually compute the partial derivatives manually: <span class="math display">\[\frac{\partial f}{\partial x_1} = \frac{1}{x_1} + x_2 = 0.5 + 5 = 5.5\]</span></p>
<p><span class="math display">\[\frac{\partial f}{\partial x_2} = x_1 - \cos(x_2) = 2 - 0.284 = 1.716\]</span></p>
<p>However, for the sake of this example, we will use Automatic Differentiation to compute these derivatives instead. The first step of Automatic Differentiation is to build up a <em>Computational Graph</em> of the function using a library of easy to compute derivatives (e.g., <span class="math inline">\(\frac{\partial}{\partial x} x^n \rightarrow n\cdot x^{n-1}\)</span>)</p>
<section id="build-the-computational-graph" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="build-the-computational-graph"><span class="header-section-number">5.1.1</span> Build the Computational Graph</h3>
<p>To build the computational graph, we break the function down into its elementary operations step by step, starting from the beginning (i.e., the inputs to the function). We will introduce intermediate variables (<span class="math inline">\(V_\#\)</span>) to represent the outputs of these intermediate operations. Let’s define:</p>
<!-- Figure source: figures/computational_graph.mmd; rendered to PNG with tools/render_mermaid.md (no live mermaid blocks in the book). -->
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/computational_graph.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>The computational graph of <span class="math inline">\(f(x_1, x_2)\)</span>.</figcaption>
</figure>
</div>
<p>Now with the graph in place, we can compute the first stage of Automatic Differentiation, which is the <em>forward pass</em> through the function.</p>
</section>
<section id="compute-the-forward-pass" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="compute-the-forward-pass"><span class="header-section-number">5.1.2</span> Compute the Forward Pass</h3>
<p>The Forward Pass is simply evaluating the function at the given input values, but we will do this step by step, following the computational graph we just built. It will be useful to keep track of the intermediate values in a table for reference later. (In reality, the computer will do this for us, but we are doing it by hand here to illustrate the process.)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 43%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Node</th>
<th>Definition</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(V0\)</span></td>
<td><span class="math inline">\(x_1\)</span></td>
<td>2</td>
</tr>
<tr class="even">
<td><span class="math inline">\(V1\)</span></td>
<td><span class="math inline">\(x_2\)</span></td>
<td>5</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(V2\)</span></td>
<td><span class="math inline">\(\ln(V0)\)</span></td>
<td><span class="math inline">\(\ln(2) \approx 0.6931\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(V3\)</span></td>
<td><span class="math inline">\(V0 \cdot V1\)</span></td>
<td><span class="math inline">\(2 \cdot 5 = 10\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(V4\)</span></td>
<td><span class="math inline">\(-\sin(V1)\)</span></td>
<td><span class="math inline">\(-\sin(5) \approx 0.9589\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(V5\)</span></td>
<td><span class="math inline">\(V2 + V3\)</span></td>
<td><span class="math inline">\(0.6931 + 10 = 10.6931\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(V6\)</span></td>
<td><span class="math inline">\(V5 + V4\)</span></td>
<td><span class="math inline">\(10.6931 + 0.9589 \approx 11.6520\)</span></td>
</tr>
</tbody>
</table>
<p>If we pass in our initial points (x1, x2) through this forward pass, we can look at the final node (V6) to get the answer: <span class="math display">\[
f(2, 5) \approx 11.6520
\]</span></p>
<p>Great, this matches what we would expect. At this point, we have just evaluated the function forward, and we don’t yet have any derivatives. From here, things get interesting and bifurcate into two main types of Automatic Differentiation: Forward Mode AD and Backward Mode AD. Each of these has important but different uses for reasons that will become clear as we work through the example. Let’s start with Forward Mode AD. In both cases, we will start with the initial work we already did with the forward pass above.</p>
</section>
<section id="computing-forward-mode-ad-tangent-propagation" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="computing-forward-mode-ad-tangent-propagation"><span class="header-section-number">5.1.3</span> Computing Forward Mode AD (tangent propagation)</h3>
<p>Forward Mode AD allows us to compute <em>directional derivatives</em> of the function, as well as that same directional derivative at <em>any intermediate node</em> in the computational graph. This is useful for computing derivatives of functions that have a small number of inputs (e.g., 1-10), but potentially a large number of outputs that we might be interested in. For example, if we were computing a trajectory of a dynamical system, we might want to know how the final state of the system changes with respect to some initial condition. In this case, the initial condition is the input, and the final state is the output. There might be many intermediate states along the way that we also want to know how they change with respect to the initial condition, such as the state or total energy at each time step. Forward Mode AD allows us to compute all of these derivatives in only a single pass through the computational graph.</p>
<p>To see how this works, we will introduce a new variable <span class="math inline">\(\dot{V}\)</span> to represent the derivative of each node with respect to some input direction. We will use the notation <span class="math inline">\(\dot{V} = \frac{dV}{dx}\)</span>, where <span class="math inline">\(x\)</span> is some input variable.</p>
<p><strong>Case A: derivative wrt <span class="math inline">\(x_1\)</span> (<span class="math inline">\(\dot{x}_1 = 1, \dot{x}_2 = 0\)</span>)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 43%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Node</th>
<th>Definition</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\dot{V_0}\)</span></td>
<td><span class="math inline">\(\dot{x_1}\)</span></td>
<td>1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\dot{V_1}\)</span></td>
<td><span class="math inline">\(\dot{x_2}\)</span></td>
<td>0</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\dot{V_2}\)</span></td>
<td><span class="math inline">\(d(\ln V_0)/dV_0 = 1/V_0 \dot{V_0}\)</span></td>
<td><span class="math inline">\((1/2)\cdot 1 = 0.5\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\dot{V_3}\)</span></td>
<td><span class="math inline">\(d(V_0 \cdot V_1)/dV_0 = \dot{V_0} V_1 + V_0 \dot{V_1}\)</span></td>
<td><span class="math inline">\(5\cdot1+2\cdot0=5\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\dot{V_4}\)</span></td>
<td><span class="math inline">\(-\cos(V_1)\dot{V_1}\)</span></td>
<td><span class="math inline">\(-\cos(5)\cdot 0 = 0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\dot{V_5}\)</span></td>
<td><span class="math inline">\(\dot{V_3} + \dot{V_2}\)</span></td>
<td><span class="math inline">\(0.5 + 5 = 5.5\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\dot{V_6}\)</span></td>
<td><span class="math inline">\(\dot{V_5} + \dot{V_4}\)</span></td>
<td><span class="math inline">\(5.5 + 0 = 5.5\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\frac{\partial f}{\partial x_1} = 5.5
\]</span></p>
<p><strong>Case B: derivative wrt <span class="math inline">\(x_2\)</span> (<span class="math inline">\(\dot{x}_1 = 0, \dot{x}_2 = 1\)</span>)</strong></p>
<p><strong>Exercise:</strong> Fill in a similar table as above to compute the derivative of the function with respect to <span class="math inline">\(x_2\)</span> using Forward Mode AD.</p>
<p>You can check your answer using the known analytical derivative of the function that you can compute by hand: <span class="math display">\[
\frac{\partial f}{\partial x_2} \approx 1.7163
\]</span></p>
<p>OK, great, we see that with some bookkeeping, we have correctly computed the derivatives of the function with respect to each input variable. Note that we had to do two passes through the computational graph to get both derivatives, since they were different directional derivatives. If we had a third input variable, we would need a third pass, and so on. This is why Forward Mode AD is best suited for functions with a small number of inputs.</p>
<p>On the flip side, if we were interested in the derivative of some intermediate node in the computational graph with respect to an input variable, we would have that information available as well. For example, if we wanted to know how <span class="math inline">\(V3\)</span> changes with respect to <span class="math inline">\(x_1\)</span>, we can see from the table above that <span class="math inline">\(\frac{\partial V3}{\partial x_1} = 5\)</span>. We got this in the process of computing the final function, so this derivative comes “along for the ride” without additional cost on our part. This is a powerful feature of Forward Mode AD that we will see is not available in Backward Mode AD: we can get a specific directional derivatives of any intermediate node from the computational graph via the same Forward Mode pass, but the cost of this scales with the number of input variables or number of directional derivatives we want to compute.</p>
</section>
<section id="computing-reverse-mode-ad-backpropagation" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="computing-reverse-mode-ad-backpropagation"><span class="header-section-number">5.1.4</span> Computing Reverse Mode AD (backpropagation)</h3>
<p>While Forward Mode AD efficiently found directional derivatives, if we wanted to compute the full gradient of the output with respect to all of the input variables, we would need to do a separate pass for each input variable. This means that the cost of computing the full gradient scales with the number of input variables. If we have a function with a large number of input variables (e.g., 1000s or more), this can be very expensive. To address this, we can use Reverse Mode AD, which will allow us to compute the full gradient of every input variable to a function using a single “backward pass” through the computational graph. This is particularly useful for functions that have a small number of outputs (e.g., 1-10), but a very large number of inputs, such as a Neural Network in Machine Learning or mesh coordinates in a Finite Element or Computational Fluid Dynamics simulation.</p>
<p>To see how this works, we will introduce a new variable <span class="math inline">\(\bar{V}\)</span> to represent the <em>adjoint</em> of each node with respect to the output. We will use the notation <span class="math inline">\(\bar{V} = \frac{\partial f}{\partial V}\)</span>, where <span class="math inline">\(f\)</span> is the final output of the function. The adjoint represents how much a small change in that intermediate node would affect the final output of the function.</p>
<p>Similarly to Forward Mode AD, we will have to pick a specific output that we wish to compute the gradient with respect to. In this case, since we are computing the gradient of the output with respect to all input variables, we can set the final output node with a value of 1, i.e., <span class="math inline">\(\bar{V6} = 1\)</span>. From there, we will propagate each adjoint backward through the computational graph using the chain rule.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 43%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Node</th>
<th>Equation for the adjoint</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\bar{V_6}\)</span></td>
<td><span class="math inline">\(\frac{\partial f}{\partial V_6}\)</span></td>
<td>1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{V_5}\)</span></td>
<td><span class="math inline">\(\frac{\partial f}{\partial V_6} \frac{\partial V_6}{\partial V_5} = \bar{V_6}1\)</span></td>
<td>1</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\bar{V_4}\)</span></td>
<td><span class="math inline">\(\frac{\partial f}{\partial V_6} \frac{\partial V_6}{\partial V_4} = \bar{V_6}1\)</span></td>
<td>1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{V_3}\)</span></td>
<td><span class="math inline">\(\frac{\partial f}{\partial V_5} \frac{\partial V_5}{\partial V_3} = \bar{V_5}1\)</span></td>
<td>1</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\bar{V_2}\)</span></td>
<td><span class="math inline">\(\frac{\partial f}{\partial V_5} \frac{\partial V_5}{\partial V_2} = \bar{V_5}1\)</span></td>
<td>1</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{V_1}\)</span></td>
<td>from V3: <span class="math inline">\(\bar{V_3}\cdot V_1=2\)</span> <br> + from V4: <span class="math inline">\(-\cos(5)\cdot \bar{V_4} \approx -0.2837\)</span></td>
<td>1.7163</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\bar{V_0}\)</span></td>
<td>from V2: <span class="math inline">\(\bar{V_2}(1/V_0)\cdot1=0.5\)</span> <br> + from V3: <span class="math inline">\(\bar{V_3}\cdot V_1=5\)</span></td>
<td>5.5</td>
</tr>
</tbody>
</table>
<p>We can now verify the final gradients, which match our analytical solution:</p>
<p><span class="math display">\[
\nabla f(2,5) = \left( \frac{\partial f}{\partial x_1}, \frac{\partial f}{\partial x_2} \right) = (5.5, \, 1.7163)
\]</span></p>
<p>However, unlike Forward Mode AD, we see that we now have access not only to the gradients of the input variables, but also to the gradients of <strong>all intermediate nodes</strong> in the computational graph, and we received all of them via the same amount of work/computation!</p>
</section>
</section>
<section id="pytorch-autograd-example-with-simple-function" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="pytorch-autograd-example-with-simple-function"><span class="header-section-number">5.2</span> PyTorch Autograd Example with Simple Function</h2>
<p>Ok let’s use automatic differentiation to compute a simple derivative of our earlier analytical function:</p>
<p><span class="math display">\[y = f(x_0,x_1) = \ln(x_0) + x_0 \cdot x_1 - \sin(x_1)\]</span></p>
<p>And as with before, we’ll evaluate the derivative of this function at <span class="math display">\[x_0 = 2, x_1=5\]</span></p>
<p>We can analytically compute the derivative and code it up so that we can verify accuracy later:</p>
<div id="39b59755" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> true_grad(x0,x1):</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array([</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        <span class="dv">1</span><span class="op">/</span>x0 <span class="op">+</span> x1,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        x0 <span class="op">-</span> np.cos(x1)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>true_grad(<span class="dv">2</span>,<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>array([5.5       , 1.71633781])</code></pre>
</div>
</div>
<p>But now let’s see how to use <a href="https://pytorch.org/">PyTorch</a> to get this using Automatic Differentiation:</p>
<section id="automatic-differentiation-using-pytorch" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="automatic-differentiation-using-pytorch"><span class="header-section-number">5.2.1</span> Automatic Differentiation using PyTorch</h3>
<div id="935826a0" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="fl">2.0</span>, <span class="fl">5.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([2., 5.], requires_grad=True)</code></pre>
</div>
</div>
<div id="3a3987f9" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f(x):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.log(x[<span class="dv">0</span>]) <span class="op">+</span> x[<span class="dv">0</span>]<span class="op">*</span>x[<span class="dv">1</span>] <span class="op">-</span> torch.sin(x[<span class="dv">1</span>])</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> f(x)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor(11.6521, grad_fn=&lt;SubBackward0&gt;)</code></pre>
</div>
</div>
<div id="92170222" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x.grad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="4ee95616" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now call the backward AD pass so that we can compute gradients</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>y.backward()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we can ask for the gradient:</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>x.grad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>tensor([5.5000, 1.7163])</code></pre>
</div>
</div>
<p>Let’s see how well it approximated the true gradient:</p>
<div id="d30be078" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>true_grad(<span class="dv">2</span>,<span class="dv">5</span>) <span class="op">-</span> x.grad.numpy()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>array([0.00000000e+00, 1.45108339e-08])</code></pre>
</div>
</div>
</section>
<section id="finite-differences-using-scipy" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="finite-differences-using-scipy"><span class="header-section-number">5.2.2</span> Finite Differences using SciPy</h3>
<p>Now let’s compare this to computing the same gradient, but using Numerical Differentiation. SciPy’s <code>approx_fprime</code> uses the one-sided (forward) difference formula from the introduction, <span class="math inline">\(\frac{f(x + \epsilon) - f(x)}{\epsilon}\)</span>, one coordinate at a time:</p>
<div id="d0c73ce5" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> optimize</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x_np <span class="op">=</span> np.array([<span class="fl">2.0</span>, <span class="fl">5.0</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f_np(x):</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.log(x[<span class="dv">0</span>]) <span class="op">+</span> x[<span class="dv">0</span>]<span class="op">*</span>x[<span class="dv">1</span>] <span class="op">-</span> np.sin(x[<span class="dv">1</span>])</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#y_np = f_np(x_np)</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># This computes finite differences opf f_np at x_np:</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>optimize.approx_fprime(x_np, f_np, epsilon<span class="op">=</span><span class="fl">1e-4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([5.4999875 , 1.71628987])</code></pre>
</div>
</div>
<p>Let’s see how well it approximated the true gradient:</p>
<div id="9b0490dd" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>true_grad(<span class="dv">2</span>,<span class="dv">5</span>) <span class="op">-</span> optimize.approx_fprime(x_np, f_np, epsilon<span class="op">=</span><span class="fl">1e-4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>array([1.24995903e-05, 4.79457300e-05])</code></pre>
</div>
</div>
<div id="b61ae322" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> numerical_error(e):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> true_grad(<span class="dv">2</span>,<span class="dv">5</span>) <span class="op">-</span> optimize.approx_fprime(x_np, f_np, epsilon<span class="op">=</span>e)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">#error = lambda e: true_grad(2,5) - optimize.approx_fprime(x_np, y_np, epsilon=e)</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>epsilons <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">13</span>,<span class="dv">1</span>,num<span class="op">=</span><span class="dv">21</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>errors <span class="op">=</span> [np.linalg.norm(numerical_error(e)) <span class="cf">for</span> e <span class="kw">in</span> epsilons]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="3edc7bfe" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sns.set_context(<span class="st">'poster'</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">1</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>plt.loglog(epsilons,errors,marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'$</span><span class="er">\</span><span class="st">epsilon$'</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Error'</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Finite Difference Approximation'</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="pytorch-autograd-example-with-optimization" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="pytorch-autograd-example-with-optimization"><span class="header-section-number">5.3</span> PyTorch Autograd Example with Optimization</h2>
<p>This example shows how to use AD and PyTorch to perform gradient based optimization on a simple test function</p>
<div id="9331d0cb" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example of the McCormick Function</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mccormick(x):</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> torch.sin(x[<span class="dv">0</span>]<span class="op">+</span>x[<span class="dv">1</span>]) <span class="op">+</span> (x[<span class="dv">0</span>]<span class="op">-</span>x[<span class="dv">1</span>])<span class="op">**</span><span class="dv">2</span> <span class="op">-</span> <span class="fl">1.5</span><span class="op">*</span>x[<span class="dv">0</span>]<span class="op">+</span><span class="fl">2.5</span><span class="op">*</span>x[<span class="dv">1</span>]<span class="op">+</span><span class="dv">1</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>f <span class="op">=</span> mccormick</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="op">-</span><span class="fl">4.0</span>, <span class="fl">4.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> f(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What does this function look like?</p>
<div id="6cd0bcca" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>X_plot <span class="op">=</span> torch.meshgrid(torch.linspace(<span class="op">-</span><span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">100</span>),torch.linspace(<span class="op">-</span><span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">100</span>), indexing<span class="op">=</span><span class="st">'ij'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>x_plot,y_plot <span class="op">=</span> X_plot</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>plt.contour(x_plot,y_plot,f(X_plot))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="34a967be" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.axes(projection<span class="op">=</span><span class="st">'3d'</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>ax.contour3D(x_plot, y_plot, f(X_plot), <span class="dv">50</span>, cmap<span class="op">=</span><span class="st">'binary_r'</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>ax.view_init(<span class="dv">40</span>, <span class="dv">90</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s say I want to optimize this. I could compute the analytical derivative. Or, I could compute the backward-mode AD on the inputs:</p>
<div id="8bd908e4" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pick a starting point:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="op">-</span><span class="fl">4.0</span>, <span class="fl">4.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate y</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> f(x)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Now call the backward AD pass so that we can compute gradients</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>y.backward()</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we can get the gradient</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>x.grad</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>tensor([-16.5000,  19.5000])</code></pre>
</div>
</div>
<section id="using-automatic-differentiation-for-optimization" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="using-automatic-differentiation-for-optimization"><span class="header-section-number">5.3.1</span> Using Automatic Differentiation for Optimization</h3>
<p>Automatic Differentiation can now gives us an gradient, which a gradient-based optimizer can then use to perform gradient descent, as we covered in a previous chapter, where the main difference is now we do not have to compute the gradients manually. Recall from our introduction to gradient descent that <span class="math inline">\(w_{t+1} = w_t - \alpha\, \nabla J(w_t)\)</span>, and that we had covered the use of momentum to accelerate and stablize vanilla SGD. As a reminder, the gradient descent with momentum step looked like the following:</p>
<p><span class="math display">\[
\begin{aligned}
v_{t+1} &amp;= \beta\, v_t + \nabla_w J(w_t) \\
w_{t+1} &amp;= w_t - \alpha\, v_{t+1}
\end{aligned}
\]</span></p>
<p>We saw with normalization that having different dimensions or curvatures in the loss landscape could induce slow convergence behavior (even with momentum), and so more advanced versions of GD are used in practice, with one of the most widely used variants being the Adam Optimizer (<span class="citation" data-cites="kingma2015adam">(<a href="../references.html#ref-kingma2015adam" role="doc-biblioref"><strong>kingma2015adam?</strong></a>)</span>), which we’ll state below and then define how this differs from regular momentum. Importantly, the original Adam paper defined the momentum term with a different symbol (<span class="math inline">\(m_t\)</span> instead of <span class="math inline">\(v_t\)</span> which we used above, and re-purposes the symbol <span class="math inline">\(v_t\)</span> to scale coordiante dimensions):</p>
<p><span class="math display">\[
\begin{aligned}
m_t &amp;= \beta_1\, m_{t-1} + (1 - \beta_1)\, \nabla_w J(w_t), \qquad v_t = \beta_2\, v_{t-1} + (1 - \beta_2)\, \nabla_w J(w_t)^2, \\
w_{t+1} &amp;= w_t - \alpha\, \frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}, \qquad \hat{m}_t = \frac{m_t}{1 - \beta_1^t}, \quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}.
\end{aligned}
\]</span></p>
<p>The square, the square root and the division are taken coordinate by coordinate, and the hats correct for both averages starting at zero. PyTorch’s defaults are <span class="math inline">\(\beta_1 = 0.9\)</span>, <span class="math inline">\(\beta_2 = 0.999\)</span> and <span class="math inline">\(\epsilon = 10^{-8}\)</span>. The average <span class="math inline">\(\hat{m}_t\)</span> plays the role of momentum. Dividing it by <span class="math inline">\(\sqrt{\hat{v}_t}\)</span>, the typical size of recent gradients, removes the scale of the gradient. If the gradient has kept the same sign for a while, the ratio is close to <span class="math inline">\(\pm 1\)</span> and the coordinate moves by about <span class="math inline">\(\alpha\)</span>, whether the slope is steep or shallow. (On the first step the ratio is exactly <span class="math inline">\(\pm 1\)</span>.) The step gets shorter when the gradient changes sign, so that positive and negative values cancel in <span class="math inline">\(\hat{m}_t\)</span>, or when the gradient becomes small compared with the earlier gradients that <span class="math inline">\(\hat{v}_t\)</span> still remembers (<span class="math inline">\(\beta_2\)</span> is close to 1, so it remembers them for a long time). This is the main difference from gradient descent: in Adam the learning rate sets the length of the step in each coordinate, and the size of the gradient does not. <strong>AdamW</strong>, which we use below, is Adam with <em>weight decay</em>: each step also multiplies <span class="math inline">\(w\)</span> by <span class="math inline">\(1 - \alpha\lambda\)</span>, which pulls it toward zero (PyTorch’s default is <span class="math inline">\(\lambda = 0.01\)</span>). You can think of this as just adding an additional L2 penalty to <span class="math inline">\(w\)</span>.</p>
<p>Let’s run AdamW on the McCormick function from the starting point <span class="math inline">\((-4, 4)\)</span>:</p>
<div id="bfd62241" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take an initial guess at the optimum:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="op">-</span><span class="fl">4.0</span>, <span class="fl">4.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The minimum in the plotted window is at about x_opt = [-0.547, -1.547] (the star in the L-BFGS plot below)</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize the optimizer</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.AdamW([x], lr<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>num_steps <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> [np.array(x.detach().numpy())]</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Take num_steps steps</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(num_steps):</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    optimizer.zero_grad()</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> f(x)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    y.backward()</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    optimizer.step()</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>        steps.append(np.array(x.detach().numpy()))</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(x)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> np.array(steps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([-2.9600,  2.9600], requires_grad=True)
tensor([-1.9481,  1.9436], requires_grad=True)
tensor([-0.9857,  0.9653], requires_grad=True)
tensor([-0.1051,  0.0453], requires_grad=True)
tensor([ 0.6508, -0.7906], requires_grad=True)
tensor([ 1.2368, -1.5138], requires_grad=True)
tensor([ 1.6219, -2.0992], requires_grad=True)
tensor([ 1.8020, -2.5325], requires_grad=True)
tensor([ 1.7979, -2.8129], requires_grad=True)
tensor([ 1.6423, -2.9514], requires_grad=True)
tensor([ 1.3704, -2.9664], requires_grad=True)
tensor([ 1.0147, -2.8804], requires_grad=True)
tensor([ 0.6043, -2.7165], requires_grad=True)
tensor([ 0.1659, -2.4983], requires_grad=True)
tensor([-0.2759, -2.2482], requires_grad=True)
tensor([-0.6981, -1.9879], requires_grad=True)
tensor([-1.0796, -1.7375], requires_grad=True)
tensor([-1.4026, -1.5143], requires_grad=True)
tensor([-1.6534, -1.3326], requires_grad=True)
tensor([-1.8238, -1.2020], requires_grad=True)
tensor([-1.9113, -1.1271], requires_grad=True)
tensor([-1.9188, -1.1078], requires_grad=True)
tensor([-1.8539, -1.1396], requires_grad=True)
tensor([-1.7274, -1.2146], requires_grad=True)
tensor([-1.5524, -1.3224], requires_grad=True)
tensor([-1.3433, -1.4512], requires_grad=True)
tensor([-1.1152, -1.5883], requires_grad=True)
tensor([-0.8830, -1.7215], requires_grad=True)
tensor([-0.6606, -1.8395], requires_grad=True)
tensor([-0.4605, -1.9328], requires_grad=True)
tensor([-0.2926, -1.9947], requires_grad=True)
tensor([-0.1641, -2.0210], requires_grad=True)
tensor([-0.0788, -2.0109], requires_grad=True)
tensor([-0.0372, -1.9664], requires_grad=True)
tensor([-0.0366, -1.8921], requires_grad=True)
tensor([-0.0720, -1.7947], requires_grad=True)
tensor([-0.1359, -1.6823], requires_grad=True)
tensor([-0.2198, -1.5637], requires_grad=True)
tensor([-0.3146, -1.4478], requires_grad=True)
tensor([-0.4113, -1.3430], requires_grad=True)
tensor([-0.5017, -1.2561], requires_grad=True)
tensor([-0.5791, -1.1926], requires_grad=True)
tensor([-0.6384, -1.1558], requires_grad=True)
tensor([-0.6769, -1.1466], requires_grad=True)
tensor([-0.6937, -1.1639], requires_grad=True)
tensor([-0.6901, -1.2045], requires_grad=True)
tensor([-0.6693, -1.2638], requires_grad=True)
tensor([-0.6353, -1.3361], requires_grad=True)
tensor([-0.5934, -1.4148], requires_grad=True)
tensor([-0.5490, -1.4935], requires_grad=True)</code></pre>
</div>
</div>
<div id="acbbb430" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plt.contour(x_plot,y_plot,f(X_plot))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>plt.plot(steps[:,<span class="dv">0</span>],steps[:,<span class="dv">1</span>],marker<span class="op">=</span><span class="st">'+'</span>,label <span class="op">=</span> <span class="st">"AdamW"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"AdamW optimizer"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="l-bfgs" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="l-bfgs"><span class="header-section-number">5.3.2</span> L-BFGS</h3>
<p>Newton’s method steps to the minimum of a local quadratic model of the function, <span class="math inline">\(w_{t+1} = x_t - H^{-1} g_t\)</span>, where <span class="math inline">\(H\)</span> is the matrix of second derivatives (the Hessian). L-BFGS (limited-memory Broyden-Fletcher-Goldfarb-Shanno) is a <em>quasi-Newton</em> method. It never forms <span class="math inline">\(H\)</span>. Instead it approximates <span class="math inline">\(H^{-1} g_t\)</span> from the changes in position and gradient over the last few iterations. Like Adam it needs only gradients, but it uses them to estimate the curvature of the function. Where the function is close to a quadratic, the L-BFGS direction points almost straight at the minimum.</p>
<p>Two details of <code>torch.optim.LBFGS</code> matter for reading the plot below. One call of <code>optimizer.step(closure)</code> runs up to <code>max_iter=20</code> L-BFGS iterations and calls <code>closure</code> once per iteration, so the 5 plotted steps contain up to 100 iterations. And unless you pass <code>line_search_fn="strong_wolfe"</code>, each iteration moves a fixed fraction <code>lr</code> of the quasi-Newton step. With <code>lr=0.05</code> that is 5% of the way to the minimum of the current quadratic model.</p>
<div id="2d85e616" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take an initial guess at the optimum:</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> torch.tensor([<span class="op">-</span><span class="fl">4.0</span>, <span class="fl">4.0</span>], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The minimum in the plotted window is at about x_opt = [-0.547, -1.547] (the star in the L-BFGS plot below)</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize the optimizer</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Here using LBFGS, which is much faster convergence on small problems</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> torch.optim.LBFGS([x],lr<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>num_steps <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> [np.array(x.detach().numpy())]</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Take num_steps steps</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(num_steps):</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> closure():</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>        optimizer.zero_grad()</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> f(x)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>        y.backward()</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> y</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    optimizer.step(closure)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>            steps.append(np.array(x.detach().numpy()))</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(x)</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> np.array(steps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([-1.9382,  0.4356], requires_grad=True)
tensor([-1.0402, -0.8307], requires_grad=True)
tensor([-0.7223, -1.2888], requires_grad=True)
tensor([-0.6097, -1.4543], requires_grad=True)
tensor([-0.5696, -1.5139], requires_grad=True)</code></pre>
</div>
</div>
<div id="649d9e16" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plt.contour(x_plot,y_plot,f(X_plot))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>plt.scatter([<span class="op">-</span><span class="fl">0.54719</span>],[<span class="op">-</span><span class="fl">1.54719</span>],marker<span class="op">=</span><span class="st">'*'</span>,label<span class="op">=</span><span class="st">"Optima"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>plt.plot(steps[:,<span class="dv">0</span>],steps[:,<span class="dv">1</span>],marker<span class="op">=</span><span class="st">'+'</span>,label <span class="op">=</span> <span class="st">"L-BFGS"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"L-BFGS optimizer"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="demonstration-of-ad-on-verlet-integration" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="demonstration-of-ad-on-verlet-integration"><span class="header-section-number">5.4</span> Demonstration of AD on Verlet Integration</h2>
<p>This notebook demonstrates how to use Automatic Differentiation to determine the gradients of the initial conditions of a dynamical system (in this case a damped oscillator). To do this, we will define a numerical routine (<a href="https://en.wikipedia.org/wiki/Verlet_integration">Verlet Integration</a>) and then use Automatic Differentiation to back propagate the gradient information from the output (Total system energy) to the initial conditions.</p>
<p>Below is a typical simulation script that is not current set up for automatic differentiation:</p>
<div id="3e8ceaa7" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co">###############################################################################</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.linspace(<span class="dv">0</span>,<span class="dv">10</span>,N)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> t[<span class="dv">1</span>] <span class="op">-</span> t[<span class="dv">0</span>]</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">###############################################################################</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># functions</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> integrate_original(F,x0,v0,gamma,dt<span class="op">=</span>dt):</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(F)   <span class="co"># number of steps = length of the force array</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># arrays are allocated and filled with zeros</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    Ef <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.zeros(N)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> np.zeros(N)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>    E <span class="op">=</span> np.zeros(N)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################    </span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># initial conditions</span></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    x[<span class="dv">0</span>] <span class="op">=</span> x0</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    v[<span class="dv">0</span>] <span class="op">=</span> v0</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Do the Verlet Integration</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>    fac1 <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> <span class="fl">0.5</span><span class="op">*</span>gamma<span class="op">*</span>dt</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>    fac2 <span class="op">=</span> <span class="fl">1.0</span><span class="op">/</span>(<span class="fl">1.0</span> <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span>gamma<span class="op">*</span>dt)</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N<span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>        vn <span class="op">=</span> fac1<span class="op">*</span>fac2<span class="op">*</span>v0 <span class="op">-</span> fac2<span class="op">*</span>dt<span class="op">*</span>x0 <span class="op">+</span> fac2<span class="op">*</span>dt<span class="op">*</span>F[i]</span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>        xn <span class="op">=</span> x0 <span class="op">+</span> dt<span class="op">*</span>vn</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>        Ef <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span>(x0<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> ((v0 <span class="op">+</span> vn)<span class="op">/</span><span class="fl">2.0</span>)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>        v0 <span class="op">=</span> vn</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>        x0 <span class="op">=</span> xn</span>
<span id="cb29-34"><a href="#cb29-34" aria-hidden="true" tabindex="-1"></a>        <span class="co"># For Plotting/Debug</span></span>
<span id="cb29-35"><a href="#cb29-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-36"><a href="#cb29-36" aria-hidden="true" tabindex="-1"></a>        v[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> vn</span>
<span id="cb29-37"><a href="#cb29-37" aria-hidden="true" tabindex="-1"></a>        x[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> xn</span>
<span id="cb29-38"><a href="#cb29-38" aria-hidden="true" tabindex="-1"></a>        E[i] <span class="op">=</span> Ef</span>
<span id="cb29-39"><a href="#cb29-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-40"><a href="#cb29-40" aria-hidden="true" tabindex="-1"></a>    Ef <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span>(x0<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> v0<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb29-41"><a href="#cb29-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-42"><a href="#cb29-42" aria-hidden="true" tabindex="-1"></a>    E[<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> Ef</span>
<span id="cb29-43"><a href="#cb29-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-44"><a href="#cb29-44" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb29-45"><a href="#cb29-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># return solution</span></span>
<span id="cb29-46"><a href="#cb29-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ( (x0,v0,Ef) , (x,v,E) )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now note how we modify the code to include AD via PyTorch (see comments and references to <code>torch</code>):</p>
<div id="3c3f5e78" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co">###############################################################################</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.linspace(<span class="dv">0</span>,<span class="dv">10</span>,N)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> t[<span class="dv">1</span>] <span class="op">-</span> t[<span class="dv">0</span>]</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">###############################################################################</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># functions</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> integrate(F,x0,v0,gamma,dt<span class="op">=</span>dt):</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(F)   <span class="co"># number of steps = length of the force array</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># arrays are allocated and filled with zeros</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">#x = torch.tensor([0.0],requires_grad=True)</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">#v = torch.zeros(N)</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    Ef <span class="op">=</span> torch.tensor([<span class="fl">0.0</span>],requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.zeros(N)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    v <span class="op">=</span> np.zeros(N)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    E <span class="op">=</span> np.zeros(N)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################    </span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># initial conditions</span></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>        x[<span class="dv">0</span>] <span class="op">=</span> x0</span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>        v[<span class="dv">0</span>] <span class="op">=</span> v0</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Do the Verlet Integration</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    fac1 <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> <span class="fl">0.5</span><span class="op">*</span>gamma<span class="op">*</span>dt</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>    fac2 <span class="op">=</span> <span class="fl">1.0</span><span class="op">/</span>(<span class="fl">1.0</span> <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span>gamma<span class="op">*</span>dt)</span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N<span class="op">-</span><span class="dv">1</span>):</span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a>        vn <span class="op">=</span> fac1<span class="op">*</span>fac2<span class="op">*</span>v0 <span class="op">-</span> fac2<span class="op">*</span>dt<span class="op">*</span>x0 <span class="op">+</span> fac2<span class="op">*</span>dt<span class="op">*</span>F[i]</span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a>        xn <span class="op">=</span> x0 <span class="op">+</span> dt<span class="op">*</span>vn</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>        Ef <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span>(x0<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> ((v0 <span class="op">+</span> vn)<span class="op">/</span><span class="fl">2.0</span>)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>        v0 <span class="op">=</span> vn</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a>        x0 <span class="op">=</span> xn</span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># For Plotting/Debug</span></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>            v[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> vn</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>            x[i <span class="op">+</span> <span class="dv">1</span>] <span class="op">=</span> xn</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a>            E[i] <span class="op">=</span> Ef</span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a>    Ef <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span>(x0<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> v0<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>        E[<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> Ef</span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a>    <span class="co">###########################################################################</span></span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>    <span class="co"># return solution</span></span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ( (x0,v0,Ef) , (x,v,E) )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="5d80bd7f" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">###############################################################################</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Do the actual numerical integration</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>F <span class="op">=</span> np.zeros(N)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>x_initial <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>], requires_grad <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>v_initial <span class="op">=</span> torch.tensor([<span class="fl">1.0</span>], requires_grad <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">#gamma = torch.tensor([0.05], requires_grad = True)</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>gamma <span class="op">=</span> torch.tensor([<span class="fl">.05</span>], requires_grad <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>((xf,vf,Ef),(x1,v1,E1)) <span class="op">=</span> integrate(F,x_initial,v_initial,gamma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="d7643dfb" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_solution(x1,E1,gamma):</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">"axes.grid"</span>] <span class="op">=</span> <span class="va">True</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">'font.size'</span>] <span class="op">=</span> <span class="dv">14</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    plt.rcParams[<span class="st">'axes.labelsize'</span>] <span class="op">=</span> <span class="dv">18</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    plt.figure()</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">211</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f"Integration with $</span><span class="er">\</span><span class="ss">gamma = </span><span class="sc">{</span><span class="bu">float</span>(gamma)<span class="sc">:.2f}</span><span class="ss">$"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    plt.plot(t,x1)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"x(t)"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">212</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    plt.plot(t,E1,label<span class="op">=</span><span class="vs">fr"</span><span class="dv">$</span><span class="er">\</span><span class="vs">gamma = </span><span class="sc">{</span><span class="bu">float</span>(gamma)<span class="sc">:.2f}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    plt.ylim(<span class="dv">0</span>,<span class="fl">1.0</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"E(t)"</span>)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Time"</span>)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>plot_solution(x1,E1,gamma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="fc69d3cb" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(Ef)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Ef.backward(retain_graph<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([0.6137], grad_fn=&lt;MulBackward0&gt;)</code></pre>
</div>
</div>
<p>Now let’s print the gradient of the system Energy with respect to some of the initial conditions:</p>
<div id="0ae26d6a" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gamma.grad)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(v_initial.grad)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(x_initial.grad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([-5.9562])
tensor([0.6026])
tensor([0.6248])</code></pre>
</div>
</div>
<p>We can do the same for the final velocity. One thing to be careful about: PyTorch <em>accumulates</em> gradients into <code>.grad</code> rather than overwriting them, so a second <code>backward</code> call would add the new gradients to the ones we just printed. We zero them first (the optimizers below do the same thing with <code>optimizer.zero_grad()</code>).</p>
<div id="6402322b" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># .grad accumulates: the gradients of Ef are still stored there, and a second</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># backward call would add to them. Clear them first.</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p <span class="kw">in</span> (gamma, v_initial, x_initial):</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    p.grad.zero_()</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(vf)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Now we can call backward on the final velocity to get the gradients of the final velocity with respect to the initial conditions and gamma.</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>vf.backward()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([-0.2245], grad_fn=&lt;AddBackward0&gt;)</code></pre>
</div>
</div>
<div id="10422313" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gamma.grad)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(v_initial.grad)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(x_initial.grad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tensor([1.2027])
tensor([-0.6463])
tensor([0.4218])</code></pre>
</div>
</div>
<section id="optimizing-the-damping-coefficient-via-sgd-and-ad" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="optimizing-the-damping-coefficient-via-sgd-and-ad"><span class="header-section-number">5.4.1</span> Optimizing the Damping Coefficient via SGD and AD</h3>
<p>First let’s just get a visual intuition for how <span class="math inline">\(\gamma\)</span> affects the final energy:</p>
<div id="9924d7c0" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>num_gammas <span class="op">=</span> <span class="dv">30</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>gamma_plot <span class="op">=</span> np.logspace(<span class="op">-</span><span class="fl">0.5</span>,<span class="fl">1.0</span>,num_gammas)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>Efs <span class="op">=</span> np.zeros(num_gammas)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i,g <span class="kw">in</span> <span class="bu">enumerate</span>(gamma_plot):</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    ((xf,vf,Ef),(x1,v1,E1)) <span class="op">=</span> integrate(F,x_initial,v_initial,g)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>    Efs[i] <span class="op">=</span> Ef</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="bb8bccde" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>plt.semilogx(gamma_plot,Efs)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="vs">r'</span><span class="dv">$</span><span class="er">\</span><span class="vs">gamma</span><span class="dv">$</span><span class="vs">'</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'E Final'</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-29-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can see that there is a pretty flat plateau from around <span class="math inline">\(\gamma=1\)</span> until around <span class="math inline">\(\gamma=3\)</span>.</p>
<p>Now let’s use our backward mode AD to actually optimize <span class="math inline">\(\gamma\)</span> directly by calling backward on the output of the final energy of the Verlet integration of the ODE:</p>
<div id="e8d1c9e0" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This part is just a helper library for plotting</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_optimization(initial_gamma, num_steps, optimizer, opt_kwargs<span class="op">=</span>{}):</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take an initial guess at the optimum:</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    gamma <span class="op">=</span> torch.tensor([initial_gamma], requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Initialize the optimizer</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> optimizer([gamma], <span class="op">**</span>opt_kwargs)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    steps <span class="op">=</span> [ ] <span class="co"># Here is where we'll keep track of the steps</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take num_steps of the optimizer</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(num_steps):</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># This function runs an actual optimization step. We wrap it in closure so that optimizers</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>        <span class="co"># that take multiple function calls per step can do so -- e.g., LBFGS.</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>        <span class="kw">def</span> closure():</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Get rid of the existing gradients on the tape</span></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Run the numerical integration -- this is the forward pass through the solver</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>            ((xf,vf,Ef),(x1,v1,E1)) <span class="op">=</span> integrate(F,x_initial,v_initial,gamma) <span class="co"># x0 = 0.0, v0 = 1.0, gamma = 0.0</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Compute the backward mode AD pass</span></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>            Ef.backward()</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> Ef</span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Now ask the optimizer to take a step</span></span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>        optimizer.step(closure)</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># The below part is just for printing/plotting. We call torch.no_grad() here to signify that</span></span>
<span id="cb43-26"><a href="#cb43-26" aria-hidden="true" tabindex="-1"></a>        <span class="co"># we do not need to track this as part of the gradient operations. That is, these parts will not</span></span>
<span id="cb43-27"><a href="#cb43-27" aria-hidden="true" tabindex="-1"></a>        <span class="co"># be added to the computational graph or used for backward mode AD.</span></span>
<span id="cb43-28"><a href="#cb43-28" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> torch.no_grad():</span>
<span id="cb43-29"><a href="#cb43-29" aria-hidden="true" tabindex="-1"></a>            <span class="co">#print(gamma)</span></span>
<span id="cb43-30"><a href="#cb43-30" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Run again just to plot the solution for this gamma</span></span>
<span id="cb43-31"><a href="#cb43-31" aria-hidden="true" tabindex="-1"></a>            ((xf,vf,Ef),(x1,v1,E1)) <span class="op">=</span> integrate(F,x_initial,v_initial,gamma)</span>
<span id="cb43-32"><a href="#cb43-32" aria-hidden="true" tabindex="-1"></a>            <span class="co">#print(Ef)</span></span>
<span id="cb43-33"><a href="#cb43-33" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> num_steps<span class="op">&gt;</span><span class="dv">10</span> <span class="kw">and</span> i<span class="op">%</span><span class="dv">3</span><span class="op">==</span><span class="dv">0</span>:</span>
<span id="cb43-34"><a href="#cb43-34" aria-hidden="true" tabindex="-1"></a>                plot_solution(x1,E1,gamma)</span>
<span id="cb43-35"><a href="#cb43-35" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Add it to steps so that we can see/plot it later.</span></span>
<span id="cb43-36"><a href="#cb43-36" aria-hidden="true" tabindex="-1"></a>            steps.append(np.array(gamma.detach().numpy()))</span>
<span id="cb43-37"><a href="#cb43-37" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb43-38"><a href="#cb43-38" aria-hidden="true" tabindex="-1"></a>    steps <span class="op">=</span> np.array(steps)</span>
<span id="cb43-39"><a href="#cb43-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> steps</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="adam-example" class="level4" data-number="5.4.1.1">
<h4 data-number="5.4.1.1" class="anchored" data-anchor-id="adam-example"><span class="header-section-number">5.4.1.1</span> Adam Example</h4>
<p>Here, we use Automatic Differentation through the integrator to optimize the dynamical system using Adam.</p>
<div id="2b523da6" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>steps_Adam <span class="op">=</span> plot_optimization(initial_gamma<span class="op">=</span><span class="fl">0.05</span>, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                               num_steps<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                               optimizer<span class="op">=</span>torch.optim.AdamW,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                               opt_kwargs<span class="op">=</span>{<span class="st">'lr'</span>:<span class="fl">0.5</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-31-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sgd-example" class="level4" data-number="5.4.1.2">
<h4 data-number="5.4.1.2" class="anchored" data-anchor-id="sgd-example"><span class="header-section-number">5.4.1.2</span> SGD Example</h4>
<p>Here is the same example, but using SGD as the optimizer:</p>
<div id="5e865a7d" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>steps_SGD <span class="op">=</span> plot_optimization(initial_gamma<span class="op">=</span><span class="fl">0.05</span>, </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>                               num_steps<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                               optimizer<span class="op">=</span>torch.optim.SGD,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                               opt_kwargs<span class="op">=</span>{<span class="st">'lr'</span>:<span class="fl">0.05</span>,<span class="st">'momentum'</span>:<span class="fl">0.9</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-32-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="l-bfgs-example" class="level4" data-number="5.4.1.3">
<h4 data-number="5.4.1.3" class="anchored" data-anchor-id="l-bfgs-example"><span class="header-section-number">5.4.1.3</span> L-BFGS Example</h4>
<p>Lastly, we can also attempt this with L-BFGS. (Warning: Per-run solves of LBFGS take a while, so don’t set num_steps too high here)</p>
<div id="930c6f23" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>steps_LBFGS <span class="op">=</span> plot_optimization(initial_gamma<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                                num_steps<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                                optimizer<span class="op">=</span>torch.optim.LBFGS,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                                opt_kwargs<span class="op">=</span>{<span class="st">'lr'</span>:<span class="fl">0.3</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="compare-the-steps-taken" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="compare-the-steps-taken"><span class="header-section-number">5.4.2</span> Compare the steps taken</h3>
<div id="63df35b0" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>plt.semilogx(gamma_plot,Efs)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>steps_Adam <span class="op">=</span> steps_Adam.flatten()</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.plot(steps_Adam,[<span class="fl">0.0</span>]<span class="op">*</span><span class="bu">len</span>(steps_Adam),<span class="st">'|'</span>, color <span class="op">=</span> <span class="st">'r'</span>, label <span class="op">=</span> <span class="st">'Adam Steps'</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plt.plot(steps_SGD,[<span class="fl">0.005</span>]<span class="op">*</span><span class="bu">len</span>(steps_SGD),<span class="st">'|'</span>, color <span class="op">=</span> <span class="st">'g'</span>, label <span class="op">=</span> <span class="st">'SGD Steps'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.plot(steps_LBFGS,[<span class="fl">0.01</span>]<span class="op">*</span><span class="bu">len</span>(steps_LBFGS),<span class="st">'|'</span>, color <span class="op">=</span> <span class="st">'k'</span>, label <span class="op">=</span> <span class="st">'LBFGS Steps'</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="vs">r'</span><span class="dv">$</span><span class="er">\</span><span class="vs">gamma</span><span class="dv">$</span><span class="vs">'</span>)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'E Final'</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Comparison of Optimizers"</span>)</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-34-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="exercises" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">5.5</span> Exercises</h2>
<p>The exercises below reuse the McCormick function <code>mccormick</code> and the Verlet integrator <code>integrate</code> from this chapter, so run the chapter’s cells first. The first two are pencil-and-paper exercises with a short autograd check at the end; the last one is meant as a longer take-home task.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 1 (~8 min): Forward mode through an unrolled solver
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kepler’s equation <span class="math inline">\(M = E - e \sin E\)</span> relates the mean anomaly <span class="math inline">\(M\)</span> of an orbit to its eccentric anomaly <span class="math inline">\(E\)</span> for an eccentricity <span class="math inline">\(e\)</span>. It has no closed-form solution for <span class="math inline">\(E\)</span>, so it is solved by iterating <span class="math inline">\(E_{k+1} = M + e \sin E_k\)</span> from <span class="math inline">\(E_0 = M\)</span>. Suppose a program runs exactly two iterations and returns two outputs, the correction <span class="math inline">\(f = E_2 - M\)</span> and the normalized orbital radius <span class="math inline">\(r = 1 - e \cos E_2\)</span>. Its computational graph, in the notation of the chapter, is</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>Definition</th>
<th>Node</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(v_1\)</span></td>
<td><span class="math inline">\(M\)</span></td>
<td><span class="math inline">\(v_7\)</span></td>
<td><span class="math inline">\(v_2 \cdot v_6\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_2\)</span></td>
<td><span class="math inline">\(e\)</span></td>
<td><span class="math inline">\(v_8\)</span></td>
<td><span class="math inline">\(v_1 + v_7 \;(= E_2)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(v_3\)</span></td>
<td><span class="math inline">\(\sin v_1\)</span></td>
<td><span class="math inline">\(f\)</span></td>
<td><span class="math inline">\(v_8 - v_1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_4\)</span></td>
<td><span class="math inline">\(v_2 \cdot v_3\)</span></td>
<td><span class="math inline">\(v_9\)</span></td>
<td><span class="math inline">\(\cos v_8\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(v_5\)</span></td>
<td><span class="math inline">\(v_1 + v_4 \;(= E_1)\)</span></td>
<td><span class="math inline">\(v_{10}\)</span></td>
<td><span class="math inline">\(v_2 \cdot v_9\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_6\)</span></td>
<td><span class="math inline">\(\sin v_5\)</span></td>
<td><span class="math inline">\(r\)</span></td>
<td><span class="math inline">\(1 - v_{10}\)</span></td>
</tr>
</tbody>
</table>
<p>Evaluate everything at <span class="math inline">\((M, e) = (0, \tfrac{1}{2})\)</span>.</p>
<ul>
<li><ol type="a">
<li>Fill in the forward pass (the value of every node) and then the forward-mode tangent table for the seed <span class="math inline">\((\dot{M}, \dot{e}) = (1, 0)\)</span>, in the style of the chapter’s Case A. Which two derivatives have you obtained, and why does one of them come out as zero?</li>
</ol></li>
<li><ol start="2" type="a">
<li>Check both outputs’ derivatives with respect to both inputs using <code>torch.autograd</code>. How many forward-mode passes would you have needed for the full table, and how many <code>backward</code> calls did you need? Why do the counts differ?</li>
</ol></li>
<li><ol start="3" type="a">
<li>If the program ran twenty iterations instead of two, what would change in your table and what would not? Why does this matter for the simulations at the end of the chapter?</li>
</ol></li>
</ul>
</div>
</div>
<div id="d8ba8c37" class="cell" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can use this code cell for this exercise, if you like.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 2 (~10 min): Reverse mode on a pump model
</div>
</div>
<div class="callout-body-container callout-body">
<p>A deliberately simplified model of a centrifugal pump takes the flow rate <span class="math inline">\(Q\)</span>, the impeller speed <span class="math inline">\(n\)</span> and the fluid density <span class="math inline">\(\rho\)</span> and returns the hydraulic power <span class="math inline">\(P_h\)</span> and the efficiency <span class="math inline">\(\eta\)</span> through the head <span class="math inline">\(H\)</span>:</p>
<p><span class="math display">\[
H = \frac{n^2}{Q}, \qquad P_h = \rho\, Q\, H, \qquad \eta = \frac{Q}{\sqrt{H}} .
\]</span></p>
<p>Its computational graph, in the notation of the chapter, is</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Node</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(v_1\)</span></td>
<td><span class="math inline">\(Q\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_2\)</span></td>
<td><span class="math inline">\(n\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(v_3\)</span></td>
<td><span class="math inline">\(\rho\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_4\)</span></td>
<td><span class="math inline">\(v_2 \cdot v_2\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(v_5\)</span></td>
<td><span class="math inline">\(v_4 / v_1 \;(= H)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(v_6\)</span></td>
<td><span class="math inline">\(\sqrt{v_5}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(v_7\)</span></td>
<td><span class="math inline">\(v_3 \cdot v_1\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(P_h\)</span></td>
<td><span class="math inline">\(v_7 \cdot v_5\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\eta\)</span></td>
<td><span class="math inline">\(v_1 / v_6\)</span></td>
</tr>
</tbody>
</table>
<p>Evaluate everything at <span class="math inline">\((Q, n, \rho) = (4, 4, 3)\)</span>.</p>
<ul>
<li><ol type="a">
<li>Sketch the graph and run the forward pass. Which node is used by both outputs, and which input is used more than once?</li>
</ol></li>
<li><ol start="2" type="a">
<li>Run a reverse-mode pass seeded at <span class="math inline">\(P_h\)</span> (that is, <span class="math inline">\(\bar{P}_h = 1\)</span>, <span class="math inline">\(\bar{\eta} = 0\)</span>) and a second one seeded at <span class="math inline">\(\eta\)</span>, in the style of the chapter’s adjoint table, and assemble the <span class="math inline">\(2 \times 3\)</span> Jacobian <span class="math inline">\(\partial (P_h, \eta) / \partial (Q, n, \rho)\)</span>. Where in the tables do contributions from different paths have to be added, and why?</li>
</ol></li>
<li><ol start="3" type="a">
<li><span class="math inline">\(\partial P_h / \partial Q\)</span> comes out as exactly zero even though <span class="math inline">\(Q\)</span> feeds the graph in two places. What cancels, and what does it say about the model?</li>
</ol></li>
<li><ol start="4" type="a">
<li>For this pump, which mode of automatic differentiation gives the full Jacobian with fewer passes, and how many? Now consider two other models: one maps 2 design parameters to a 200-sample pressure trace, the other maps 200 blade-surface coordinates to one efficiency number. Which mode would you use for each, how many passes does it take, and what does reverse mode cost that forward mode does not?</li>
</ol></li>
<li><ol start="5" type="a">
<li>Check your Jacobian with <code>torch.autograd</code>. Why do you need to be careful with <code>.grad</code> between the two <code>backward</code> calls?</li>
</ol></li>
</ul>
</div>
</div>
<div id="d1e4fcee" class="cell" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can use this code cell for this exercise, if you like.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 3 (~8 min): Reading the optimizer paths
</div>
</div>
<div class="callout-body-container callout-body">
<p>Look again at the two McCormick paths the chapter produced from the start <span class="math inline">\((-4, 4)\)</span>: AdamW with <code>lr=1</code> for 50 steps, and L-BFGS with <code>lr=0.05</code> for 5 calls of <code>step</code>.</p>
<ul>
<li><ol type="a">
<li>Use the chapter’s description of each optimizer to explain the shape of its path. Why does the AdamW path run past the valley and loop around before settling, and why does the L-BFGS path run almost straight to the minimum?</li>
</ol></li>
<li><ol start="2" type="a">
<li>The cell below reruns both optimizers, with the same settings, from the start <span class="math inline">\((3, 3)\)</span> and plots the paths on a wider window. Where does each optimizer end up, and why does each end where it does?</li>
</ol></li>
<li><ol start="3" type="a">
<li>The chapter marks <span class="math inline">\((-0.547, -1.547)\)</span> as the optimum. What do these two runs tell you about that claim, and what should you check before trusting where any optimizer stops?</li>
</ol></li>
</ul>
</div>
</div>
<p>Run the cell below to produce the figure for Exercise 3 (b).</p>
<div id="ec22c993" class="cell" data-execution_count="36">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>AdamW ends at (-11.59, -12.59) with f = -11.27
L-BFGS ends at (2.60, 1.60) with f = 1.23</code></pre>
</div>
</div>
<hr>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 4 (~8 min): Vanishing and exploding gradients
</div>
</div>
<div class="callout-body-container callout-body">
<p>The logistic map</p>
<p><span class="math display">\[
x_{k+1} = r\, x_k (1 - x_k)
\]</span></p>
<p>is a one-line model of a quantity that grows in proportion to itself and saturates at 1, such as a population or the market share of a product. It has the same structure as the time-stepping loop of a simulator: the same function is applied to its own output again and again. The cell below runs 40 steps from <span class="math inline">\(x_0 = 0.2\)</span> for <span class="math inline">\(r = 2.5\)</span> and for <span class="math inline">\(r = 3.9\)</span>, calls <code>backward</code> on <span class="math inline">\(x_{40}\)</span>, and plots the iterates and the adjoints <span class="math inline">\(\bar{x}_k = \partial x_{40} / \partial x_k\)</span> that reverse mode passes back through the loop (<code>retain_grad</code> keeps them after the backward pass).</p>
<ul>
<li><ol type="a">
<li>Use the chain rule to write <span class="math inline">\(\bar{x}_k\)</span> as a product of local derivatives, one per step. For <span class="math inline">\(r = 2.5\)</span> the iterates settle at a fixed point. Find the fixed point and the local derivative there by hand, and predict by what factor <span class="math inline">\(|\bar{x}_k|\)</span> changes from one step to the next. Check your prediction against the plot and the printed values. Why is the curve a straight line?</li>
</ol></li>
<li><ol start="2" type="a">
<li>For <span class="math inline">\(r = 3.9\)</span> the iterates stay between 0 and 1 at every step, yet <span class="math inline">\(|\partial x_{40} / \partial x_0|\)</span> is about <span class="math inline">\(10^{9}\)</span>. How can both be true? What does this tell you about judging whether a loop’s gradient is usable from its forward values?</li>
</ol></li>
<li><ol start="3" type="a">
<li>Suppose <span class="math inline">\(x_0\)</span> were a parameter that you fit by gradient descent on a loss that depends on <span class="math inline">\(x_{40}\)</span>. What happens to the gradient step for each value of <span class="math inline">\(r\)</span>, and why does a longer loop make both cases worse? Many Neural Network models apply the same small function to their own output at every step of a sequence, such as in Recurrent neural networks, which are used for time series. What would you expect of their gradients, and how does it relate to the behavior you saw with the logistic map?</li>
</ol></li>
</ul>
</div>
</div>
<div id="7ecf382c" class="cell" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> logistic_adjoints(r, x0<span class="op">=</span><span class="fl">0.2</span>, n_steps<span class="op">=</span><span class="dv">40</span>):</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Run n_steps of the logistic map from x0; return the iterates x_k and the adjoints d x_N / d x_k."""</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> [torch.tensor(x0, dtype<span class="op">=</span>torch.float64, requires_grad<span class="op">=</span><span class="va">True</span>)]</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(n_steps):</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>        x_next <span class="op">=</span> r <span class="op">*</span> xs[<span class="op">-</span><span class="dv">1</span>] <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> xs[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>        x_next.retain_grad()               <span class="co"># keep this node's adjoint after the backward pass</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>        xs.append(x_next)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    xs[<span class="op">-</span><span class="dv">1</span>].backward()</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>    iterates <span class="op">=</span> np.array([x.item() <span class="cf">for</span> x <span class="kw">in</span> xs])</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>    adjoints <span class="op">=</span> np.array([x.grad.item() <span class="cf">for</span> x <span class="kw">in</span> xs])</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> iterates, adjoints</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>rates <span class="op">=</span> [<span class="fl">2.5</span>, <span class="fl">3.9</span>]</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>fig, (ax_x, ax_adj) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> rates:</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>    iterates, adjoints <span class="op">=</span> logistic_adjoints(r)</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>    ax_x.plot(iterates, <span class="st">'o-'</span>, ms<span class="op">=</span><span class="dv">4</span>, label<span class="op">=</span><span class="ss">f"r = </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>    ax_adj.semilogy(np.<span class="bu">abs</span>(adjoints), <span class="st">'o-'</span>, ms<span class="op">=</span><span class="dv">4</span>, label<span class="op">=</span><span class="ss">f"r = </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"r = </span><span class="sc">{</span>r<span class="sc">}</span><span class="ss">: x_40 = </span><span class="sc">{</span>iterates[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">, dx_40/dx_0 = </span><span class="sc">{</span>adjoints[<span class="dv">0</span>]<span class="sc">:.2e}</span><span class="ss">, "</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"adjoints at k = 40, 39, 38, 37: "</span> <span class="op">+</span> <span class="st">", "</span>.join(<span class="ss">f"</span><span class="sc">{</span>a<span class="sc">:.4g}</span><span class="ss">"</span> <span class="cf">for</span> a <span class="kw">in</span> adjoints[:<span class="op">-</span><span class="dv">5</span>:<span class="op">-</span><span class="dv">1</span>]))</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>ax_x.set_xlabel(<span class="st">"step k"</span>)</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>ax_x.set_ylabel(<span class="st">"$x_k$"</span>)</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>ax_x.set_title(<span class="st">"Iterates"</span>)</span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>ax_adj.set_xlabel(<span class="st">"step k"</span>)</span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>ax_adj.set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="cf">|</span><span class="dv">\b</span><span class="vs">ar{x}_k</span><span class="cf">|</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>ax_adj.set_title(<span class="vs">r"Adjoints </span><span class="dv">$</span><span class="er">\</span><span class="vs">partial x_</span><span class="op">{40}</span><span class="vs"> / </span><span class="er">\</span><span class="vs">partial x_k</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>ax_adj.legend(loc<span class="op">=</span><span class="st">'center left'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="fl">0.5</span>))   <span class="co"># outside the axes, so it covers no data</span></span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r = 2.5: x_40 = 0.6000, dx_40/dx_0 = 2.73e-12, adjoints at k = 40, 39, 38, 37: 1, -0.5, 0.25, -0.125
r = 3.9: x_40 = 0.8912, dx_40/dx_0 = -6.37e+09, adjoints at k = 40, 39, 38, 37: 1, 1.143, -3.559, 3.87</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-38-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 5 (~10 min): A heat exchanger formula with a hidden trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The heat duty of a heat exchanger with overall heat transfer coefficient <span class="math inline">\(U\)</span> and area <span class="math inline">\(A\)</span> is <span class="math inline">\(\dot{Q} = U A\, \Delta T_\mathrm{lm}\)</span>, where the log-mean temperature difference</p>
<p><span class="math display">\[
\Delta T_\mathrm{lm} = \frac{\Delta T_1 - \Delta T_2}{\ln(\Delta T_1 / \Delta T_2)}
\]</span></p>
<p>combines the temperature differences <span class="math inline">\(\Delta T_1\)</span> and <span class="math inline">\(\Delta T_2\)</span> between the two fluids at the two ends of the exchanger. When <span class="math inline">\(\Delta T_1 = \Delta T_2\)</span>, which happens in a counterflow exchanger whose two streams have equal heat capacity rates, the formula reads <span class="math inline">\(0/0\)</span>, but its limit is simply <span class="math inline">\(\Delta T_1\)</span>. The cell below writes the formula in PyTorch and evaluates it and its autograd derivative <span class="math inline">\(\partial \Delta T_\mathrm{lm} / \partial \Delta T_1\)</span> at <span class="math inline">\(\Delta T_2 = 50\)</span> K and <span class="math inline">\(\Delta T_1 = 50\,\mathrm{K} + \delta\)</span>, for <span class="math inline">\(\delta\)</span> from 10 K down to <span class="math inline">\(10^{-4}\)</span> K, once in <code>float32</code> (PyTorch’s default) and once in <code>float64</code>.</p>
<ul>
<li><ol type="a">
<li>Before running the cell, what value should <span class="math inline">\(\partial \Delta T_\mathrm{lm} / \partial \Delta T_1\)</span> approach as <span class="math inline">\(\delta \to 0\)</span>? Why?</li>
</ol></li>
<li><ol start="2" type="a">
<li>Run the cell. Down to which <span class="math inline">\(\delta\)</span> is the <code>float32</code> value accurate, and down to which <span class="math inline">\(\delta\)</span> is the <code>float32</code> derivative accurate? Why does the derivative fail at a much larger <span class="math inline">\(\delta\)</span> than the value? What happens at <span class="math inline">\(\delta = 0\)</span>, and why?</li>
</ol></li>
<li><ol start="3" type="a">
<li>A design optimizer that adjusts the flow rates by gradient descent may approach balanced flow. What gradients would it receive there? Change <code>lmtd</code> so that its derivative can be trusted for every <span class="math inline">\(\delta\)</span>, including <span class="math inline">\(\delta = 0\)</span>, and explain why your change works. Why is switching to <code>float64</code> not enough?</li>
</ol></li>
</ul>
</div>
</div>
<div id="48ab95ad" class="cell" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lmtd(dT1, dT2):</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Log-mean temperature difference for end temperature differences dT1 and dT2."""</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (dT1 <span class="op">-</span> dT2) <span class="op">/</span> torch.log(dT1 <span class="op">/</span> dT2)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> lmtd_and_slope(delta, dtype):</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""lmtd and its autograd derivative with respect to dT1, at dT1 = 50 + delta and dT2 = 50 (kelvin)."""</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    dT1 <span class="op">=</span> torch.tensor(<span class="fl">50.0</span> <span class="op">+</span> delta, dtype<span class="op">=</span>dtype, requires_grad<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    dT2 <span class="op">=</span> torch.tensor(<span class="fl">50.0</span>, dtype<span class="op">=</span>dtype)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>    value <span class="op">=</span> lmtd(dT1, dT2)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    value.backward()</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> value.item(), dT1.grad.item()</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>deltas <span class="op">=</span> np.logspace(<span class="dv">1</span>, <span class="op">-</span><span class="dv">4</span>, <span class="dv">26</span>)        <span class="co"># K, from 10 down to 1e-4</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>fig, (ax_value, ax_slope) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">5</span>))</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dtype <span class="kw">in</span> (torch.float32, torch.float64):</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a>    values, slopes <span class="op">=</span> <span class="bu">zip</span>(<span class="op">*</span>[lmtd_and_slope(delta, dtype) <span class="cf">for</span> delta <span class="kw">in</span> deltas])</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a>    name <span class="op">=</span> <span class="bu">str</span>(dtype).replace(<span class="st">"torch."</span>, <span class="st">""</span>)</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>    ax_value.semilogx(deltas, values, <span class="st">'o-'</span>, ms<span class="op">=</span><span class="dv">4</span>, label<span class="op">=</span>name)</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>    ax_slope.semilogx(deltas, slopes, <span class="st">'o-'</span>, ms<span class="op">=</span><span class="dv">4</span>, label<span class="op">=</span>name)</span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>ax_slope.set_yscale(<span class="st">'symlog'</span>, linthresh<span class="op">=</span><span class="dv">1</span>)   <span class="co"># linear between -1 and 1, logarithmic outside</span></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>ax_value.set_xlabel(<span class="vs">r"</span><span class="dv">$\d</span><span class="vs">elta</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">K</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>ax_value.set_ylabel(<span class="vs">r"</span><span class="dv">$\D</span><span class="vs">elta T_</span><span class="dv">\m</span><span class="vs">athrm{lm}</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">K</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a>ax_value.set_title(<span class="st">"Value"</span>)</span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>ax_slope.set_xlabel(<span class="vs">r"</span><span class="dv">$\d</span><span class="vs">elta</span><span class="dv">$</span><span class="vs"> </span><span class="kw">(</span><span class="vs">K</span><span class="kw">)</span><span class="vs">"</span>)</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>ax_slope.set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">partial </span><span class="dv">\D</span><span class="vs">elta T_</span><span class="dv">\m</span><span class="vs">athrm{lm} / </span><span class="er">\</span><span class="vs">partial </span><span class="dv">\D</span><span class="vs">elta T_1</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>ax_slope.set_title(<span class="st">"Autograd derivative"</span>)</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a>ax_slope.legend(loc<span class="op">=</span><span class="st">'center left'</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="fl">0.5</span>))</span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> delta <span class="kw">in</span> [<span class="fl">1.0</span>, <span class="fl">1e-2</span>, <span class="fl">1e-4</span>, <span class="fl">0.0</span>]:</span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"delta = </span><span class="sc">{</span>delta<span class="sc">:g}</span><span class="ss"> K: "</span> <span class="op">+</span> <span class="st">"; "</span>.join(</span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span><span class="bu">str</span>(dtype)<span class="sc">.</span>replace(<span class="st">'torch.'</span>, <span class="st">''</span>)<span class="sc">}</span><span class="ss">: value </span><span class="sc">{</span>v<span class="sc">:.4f}</span><span class="ss">, derivative </span><span class="sc">{</span>s<span class="sc">:.4g}</span><span class="ss">"</span></span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> dtype <span class="kw">in</span> (torch.float32, torch.float64) <span class="cf">for</span> v, s <span class="kw">in</span> [lmtd_and_slope(delta, dtype)]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>delta = 1 K: float32: value 50.4984, derivative 0.4967; float64: value 50.4983, derivative 0.4967
delta = 0.01 K: float32: value 50.0181, derivative -0.8125; float64: value 50.0050, derivative 0.5
delta = 0.0001 K: float32: value 48.9412, derivative 1.045e+04; float64: value 50.0001, derivative 0.5
delta = 0 K: float32: value nan, derivative nan; float64: value nan, derivative nan</code></pre>
</div>
</div>
<div id="0ca4acd0" class="cell" data-execution_count="39">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can use this code cell for this exercise, if you like.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 6 (~15 min): Fit damping and stiffness together (take-home)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The chapter fitted the damping <span class="math inline">\(\gamma\)</span> of the oscillator by gradient descent through the simulator, with the stiffness fixed at one. Now suppose both the damping and stiffness are unknown. The cell below produces a measured displacement record <code>x_measured</code> of a unit-mass oscillator with unknown damping <span class="math inline">\(\gamma\)</span> and stiffness <span class="math inline">\(k\)</span>, released from <span class="math inline">\(x_0 = 1\)</span> with <span class="math inline">\(v_0 = 1\)</span>, sampled at the <code>N_record</code> times in <code>t_record</code> with some measurement noise.</p>
<ul>
<li><ol type="a">
<li>Extend the chapter’s integrator so that the restoring force is <span class="math inline">\(-k\,x\)</span> with <span class="math inline">\(k\)</span> a parameter, and so that it returns the positions as a tensor autograd can see (the chapter’s version only stores them as NumPy arrays). Define the loss as the mean squared difference between the simulated and measured positions. Implement this however you like.</li>
</ol></li>
<li><ol start="2" type="a">
<li>Fit <span class="math inline">\(\gamma\)</span> and <span class="math inline">\(k\)</span> jointly from <code>x_measured</code>, once with Adam and once with L-BFGS, starting both from <span class="math inline">\(\gamma = 0.1\)</span>, <span class="math inline">\(k = 1\)</span>. Report the two parameter estimates and the final loss of each. Which optimizer gets there, which gets close, and why?</li>
</ol></li>
<li><ol start="3" type="a">
<li>Fitting <span class="math inline">\(\gamma\)</span> alone with <span class="math inline">\(k\)</span> known worked with any of the chapter’s optimizers. Why is the joint fit harder? What feature of the trajectory pins down <span class="math inline">\(k\)</span>, what feature pins down <span class="math inline">\(\gamma\)</span>, and how can a wrong <span class="math inline">\(k\)</span> be partly compensated by a wrong <span class="math inline">\(\gamma\)</span>? A plot of the loss over a grid of <span class="math inline">\((\gamma, k)\)</span> pairs will help you argue.</li>
</ol></li>
</ul>
</div>
</div>
<p>Run the cell below to produce the measured record for Exercise 6.</p>
<div id="11bf595f" class="cell" data-execution_count="40">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="taking_derivatives_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="38b8f873" class="cell" data-execution_count="41">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can use this code cell for this exercise, if you like.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../part1/linear_decompositions.html" class="pagination-link" aria-label="Review of Linear Unsupervised Learning">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Review of Linear Unsupervised Learning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../part1/distribution_distance.html" class="pagination-link" aria-label="Measuring Distribution Distances">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Measuring Distribution Distances</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Machine Learning for Mechanical Engineers © 2025 by <a href="../index.html#sec-contributors">Mark Fuge and IDEAL Lab Contributors</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>